namespace Specflow.NCrunch
{
    using System.CodeDom;
    using TechTalk.SpecFlow.Generator.CodeDom;

    // ReSharper disable once InconsistentNaming
    /// <summary>
    /// Interface which defines the contract for classes which will provide the NCrunch attributes to decorate the tests that are generated by SpecFlow
    /// </summary>
    public interface INCrunchAttributeProvider
    {
        /// <summary>
        /// Provides the attribute to SpecFlow
        /// </summary>
        /// <param name="codeDomHelper">Helper that is used to add the attribute to the generated code file.</param>
        /// <param name="method">The method that is being attributed.</param>
        /// <param name="nCrunchAttributeIdentifier">The part of the attribute before the underscore which will identify the specific NCrunch attribute to be used.</param>
        /// <param name="nCrunchAttributeParameters">The value remaining from the SpecFlow attribute which is not the NCrunch attribute identitifer which represent the parameter(s) to be passed to the NCrunch attribiute</param>
        /// <returns>A code attribute declaration which represents the new attribute to be added to the generated test method which NCrunch can use.</returns>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "n")]
        CodeAttributeDeclaration ProvideAttribute(CodeDomHelper codeDomHelper, CodeMemberMethod method, string nCrunchAttributeIdentifier,
            string nCrunchAttributeParameters);
    }
}